# This test.yml file runs the haskell tests using stack and bash.

name: Haskell Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 'latest'
          cabal-version: 'latest'
      - name: Install dependencies
        run: stack setup && stack build
      - name: Run tests
        run: stack test --fast --no-run-benchmarkss
      - name: Run additional tests
        run: ./test/run-tests.sh